### ISSUE TITLE
Make sure the linter docker image throws

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#119]
With some builds the linter docker image throws an error, but the github action does not show this error. Make sure this does not happen.

**Comment by Taepper** [comment]
The linter is IMO a little too strict currently. (forcing #includes which are then detected as unused by CLion)
At some point in the near future we should definitely fix the linter, such that it throws again.
I would move it away from prioritized for now, though

**Comment by JonasKellerer** [comment]
As discussed, we reintroduce the linter after #85 is finished. Then we create a pull request with all the fixes. Also we do not use the import linter, because it does not work well with clion.
