### ISSUE TITLE
Full comparison of Umbra Strings

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#137]
As a follow-up to #135 , where we want to have strings structs of fixed length that can be comparable by equality, we need to decide what happen when a user filters using another predicate.

**Comment by chaoran-chen** [comment]
What do you mean exactly? Like prefix comparisons?

**Comment by Taepper** [comment]
Generally a comparison other than equality on the new strings (which was currently also not exposed to the user as a filter expression). Note that order by is unaffected by the internal change of string representations

**Comment by Taepper** [comment]
We already support working regex search for string columns. Another operator like < for string columns is currently not planned. This will be accordingly implemented in case we need this operation
