### ISSUE TITLE
Rework data test path

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#138]
Currently the path for the tests has to be provided differently for the different use cases:

- from the terminal (`build/silo_test`):
  - then the preprocessingConfig has to specify `./testBaseData/`
- using the Dockerfile (`docker run -d -v $(pwd)/testBaseData:/data -p 8081:8081 -t silo --api --preprocessingConfig=./preprocessing_config_for_ci.yaml --databaseConfig=./test_database_config.yaml` 
  - then the preprocessing config has to specify `./`
  - this is also the reason, why the endToEnd tests need their own preprocessing config
- using clion
  -  here the user can specify, that the tests are run from `..` and so the same can used as in the terminal case

This is quite confusing and needs updating.

A possible solution would be to put the unit test data into a folder named `data` inside `testBaseData`, so that it is similar to the case, when the data is used in the Docker file. Additionally, good default values can help, so that the filename for the config do not have to be specified. Similarly, the path inside the preprocessingConfig can have their own default value, so the user does not have to specify so much.

**Comment by JonasKellerer** [comment]
This problem also came up in https://github.com/GenSpectrum/servers/pull/7

**Comment by fengelniederhammer** [comment]
Is this actually still an issue? We reworked the whole path with defaults etc. quite a bit.

**Comment by JonasKellerer** [comment]
This issue can be closed, since it is already done in #190
