### ISSUE TITLE
Consider recombinant lineages

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#143]
Currently only filters for non-recombinant lineages are allowed. We should also allow recombinant lineages.

**Comment by chaoran-chen** [comment]
I.e., at the moment, it's not possible to filter `XBB.1*`?

**Comment by Taepper** [comment]
Yes. The change in the filtering should be minimal, storage lineages must be a little adapted, should we prioritize this?

**Comment by chaoran-chen** [comment]
This would be required to replace LAPIS for COVID
