### ISSUE TITLE
Deal with Null values

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#148]
Currently some column types cannot deal with null values. Null Values are given as `?` or empty strings in the tsv file for a field. See also https://docs.nextstrain.org/projects/ncov/en/latest/guides/data-prep/local-data.html#missing-metadata

String columns will parse them as is. User can filter them by typing in a question mark or empty string themselves.

Int columns need to be adapted `INT32_MIN` will be reserved for null values

Float columns are adapted and `NAN` will be used for null values

PangoLineages and Dates have a special datatype and parsing already where null will be added

**Comment by chaoran-chen** [comment]
When performing aggregation, what is the JSON output going to look like? Is it going to be the same as LAPIS 1 where nulls/unknowns are returned as a JSON null? (e.g., `{"country":null,"count":6443}`)

Regarding strings: I think that empty strings in the TSV should be interpreted as null. Question marks should be taken as-is (and if a question mark means null, it is the task of the instance maintainer to clean the data and remove question marks before passing them to SILO)

**Comment by Taepper** [comment]
Alright, then we will do that!
