### ISSUE TITLE
Make maybe-mode disableable

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS-SILO#171]
The Maybe expressions are needed for CoV-Spectrum but for many other use cases/users, I imagine that they won't be needed. Would we be able to save a lot of memory if they are disabled?

(@Taepper)

**Comment by Taepper** [comment]
Hmm, I anyways had a change of ambiguous symbol storage in mind, as those indexes are mostly empty. But yes, we can save some memory by that. As will not really slow down maybe queries, I would not make it disablable which would require us to maintain two versions. I would suggest, will just optimize less for Maybe queries

**Comment by Taepper** [comment]
This would increase the code complexity by a lot. Speed and memory would remain largely unaffected
