### ISSUE TITLE
Test for invalid configurations and input files

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#225]
We should more extensively test the behavior when diverging from the happy path.

Here the error messages should be descriptive for a user to solve the problem

**Comment by fengelniederhammer** [comment]
Mind https://github.com/GenSpectrum/LAPIS-SILO/pull/215#discussion_r1413702056 and improve log messages

**Comment by fengelniederhammer** [comment]
duplicate of #129
