### ISSUE TITLE
Testing framework for different datasets

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#226]
We have a nice framework for dynamically adding queries that the database should be tested for. Having an easy way to add additional datasets that the preprocessing and basic functionality will be tested for would greatly increase reliability

Maybe this should then be used in #225

**Comment by fengelniederhammer** [comment]
* Easy setup for datasets and executing queries on it was mostly done in #290 
* More flexible testing of the preprocessing will have to be done in #129 anyway

So I'm closing this, since I don't think that we need this as a separate issue anymore.
