### ISSUE TITLE
Return alias of pango lineage in response

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#242]
LAPIS v1 returns the alias of a pango lineage, if requested. For example an aggregated request with fields `NEXTCLADEPANGOLINEAGE` returns `{ nextcladePangoLineage: 'JN.1.1.1', count: 2 },`. 

Currently, SILO returns `{ count: 2, nextcladePangoLineage: 'B.1.1.529.2.86.1.1.1.1' },`. 

When I recall correctly, we decided, that SILO should also return the alias, if not queried with an additional option?

**Comment by Taepper** [comment]
For all pango lineage columns, the system should automatically add two string columns that contain the aliased and unaliased pango lineages.

For queries, I propose that the user must specify the column explicitly.

My proposition the column name as in the config contains the data as in the input file (`BA.1`), whereas the second column has the name `'{name}_unaliased'` contains it without an alias (`B.1.1.529.1`)
