### ISSUE TITLE
Start without data

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS-SILO#244]
As just discussed in Slack, it should be possible to start SILO properly with a schema but without data. Currently, it might throw errors such as "Error from SILO: Metadata field country not found." when it is started without a serialized state. Such an error message is very confusing.

**Comment by fengelniederhammer** [comment]
Did we try whether we can simply start it with empty data? That would result in a correct schema (i.e. the errors are gone), but not showing data for anything.

**Comment by corneliusroemer** [comment]
Any progress here? It can cause a lot of warnings/errors/complications that one can't start SILO with empty data

**Comment by Taepper** [comment]
Ah, sorry. I started a few weeks ago, but then it got stale as some urgency regarding my PhD came up..

Will do this now!

**Comment by corneliusroemer** [comment]
Gentle ping @Taepper 🙃 This would really be very useful for downstream users 🙈

**Comment by Taepper** [comment]
Time estimate is to have it finished by tomorrow

**Comment by corneliusroemer** [comment]
I see this is almost ready now, thanks a lot @Taepper 😄

**Comment by Taepper** [comment]
Sorry for the additional incurred delay! It was blocked by 2 other issues.. one refactoring which was bigger but necessary to solve this nicely, but unfortunately it was breaking for the api.. this was then in turn blocked by the introduction of versioning for the serialized output, for smoother transitioning to new versions
