### ISSUE TITLE
Configuration of input columns

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#250]
Add the functionality, so that the maintainer can specify the displayed name differently from the name in the input data. This would add the flexibility to have multiple columns with the same underlying data. 

A possible config could look like
` 
...
- name: pango_lineage
  type: pango_lineage
  nameInData: pango_lineage
- name: pango_lineage_raw
  type: string
  nameInData: pango_lineage
...
The config name "nameInData" is up for debate.

**Comment by JonasKellerer** [comment]
Silo would store the data twice. This is only convenience. This way the user does not have to change the data, when he/she wants only to change the name. (And we could store the raw pango lineage data directly :) )

**Comment by chaoran-chen** [comment]
I see. I'm not sure how valuable this feature would be and whether it would be worth the additional code. Maybe we can discuss it in one of the upcoming planning meetings?
