### ISSUE TITLE
Return also unaliased pango lineage

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#251]
After #242 the user always gets the alias of the pango lineage. Here we add the functionality almost back.

Consider the following config:
`
    - name: PangoLineage
      type: pango_lineage
`

When a column is marked as `pango_lineage` then a filter to that name (`orderBy=PangoLineage`) should still return the aliased pango lineage. The user should now also be able to `orderBy=PangoLineage_unaliased`.

**Comment by Taepper** [comment]
This can be implemented by the maintainer of a SILO instance but is not considered the responsibility of the database
