### ISSUE TITLE
Throw an error when there is no database loaded yet

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS-SILO#295]
So that it doesn't show "count = 0" when it's still loading the initial database.

**Comment by fengelniederhammer** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

We could throw "503 Service Unavailable" and set a configurable Retry-After header. From experience, maintainers will roughly know how long SILO takes to read initial data, so they could pass that value into SILO. We could set the header to "start time of SILO + initial startup period".

On CoV-Spectrum, we could check that header and display a message when users should try again.

@chaoran-chen @Taepper ?

**Comment by Taepper** [comment]
I think there are many ways to go about this and it is also related to #244, and is in some sense orthogonal to it

A check on the data version would also be possible to see that no data has been loaded (but a schema could already be loaded once #244 is implemented)

**Comment by chaoran-chen** [comment]
The 503 and Retry-After idea sounds good to me.
