### ISSUE TITLE
Fix caching of docker image for GH action

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#339]
Currently, we try to cache the build step of the docker images (Dockerfile and Dockerfile_linter). This way, we do not need to build the dependencies each time the ci runs. The cache seems to work for the Dockerfile_linter.linter_dependencies. It does not work for Dockerfile.dep_builder. This should be fixed.

**Comment by Taepper** [comment]
This was partly fixed with manual dependency image caching in #374
Some problems might persist, but we will reopen an appropriate issue when symptoms arise
