### ISSUE TITLE
Clean up includes

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#36]
The header files have currently many transitive includes. This makes refactoring harder. So we could clean up the includes, that every header file includes everything directly, what it uses.

There is a tool already available, which automates the checks: [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) which comes with native support for cmake.

**Comment by JonasKellerer** [comment]
Maybe this works directly, when iwyu is installed
`#find_program(IWYU_PATH NAMES include-what-you-use iwyu)
#set(CMAKE_CXX_INCLUDE_WHAT_YOU_USE ${IWYU_PATH})`

**Comment by Taepper** [comment]
Can we close this issue?

**Comment by JonasKellerer** [comment]
I think so. Thanks.
