### ISSUE TITLE
DOC: Document the config schema

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS-SILO#365]
I've struggled with the SILO config schema before, is it documented anywhere?

In particular the allowed values and their combinations for metadata schema are unclear. Sometimes certain fields require other fields to be present. IIRC, if you set autogenerate index, the field has to be string, otherwise there's an error, and more stuff like this.

I mean this config: https://github.com/GenSpectrum/LAPIS-SILO/blob/main/testBaseData/test_database_config.yaml

I couldn't find a specification/docs for it during a brief search

It's quite important to know what is supported for configuring a database that uses SILO

**Comment by fengelniederhammer** [comment]
It's documented in the LAPIS docs:
https://github.com/GenSpectrum/LAPIS/tree/main/lapis2-docs/src/content/docs

They are deployed e.g. here: https://lapis.cov-spectrum.org/gisaid/v2/docs/maintainer-docs/references/database-configuration

**Comment by corneliusroemer** [comment]
Ah thanks! I didn't even know they existed. I couldn't find a link to them in the readme - would be good to add a "docs" section, and also add the docs as link here:
<img width="692" alt="image" src="https://github.com/GenSpectrum/LAPIS-SILO/assets/25161793/c9c32004-45ad-4a2b-b3c0-94e05c9ff204">

**Comment by chaoran-chen** [comment]
The documentation is instance specific and we don't have a general documentation page, yet.
