### ISSUE TITLE
Q: Is pangoLienageDefinitionFilename mandatory config field?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS-SILO#369]
Only SARS-CoV-2 has pango lineages per se, there's something a bit like pango for mpox, and similar (but different) systems for flu, rsv etc

Is the lineage config field required? That would not make much sense, making it optional would be better.

In general, it might be good to come up with a general way of dealing with aliases that isn't pango specific.

I can help come up with something for the ones that works at least for those nomenclature schemes that are quite similar to pango: mpox, flu, rsv

**Comment by Taepper** [comment]
I would gladly discuss this with you! I had quite clear plans that @JonasKellerer partly implemented, but was left in a WIP state. It would be great to discuss whether it is sensible and your thoughts on this.

Overall: I would like to turn the Pango Alias system into a generic format for tree/hierarchical column types that are also possible to have multiple roots (i.e. more a forest than a tree)

**Comment by fengelniederhammer** [comment]
You're referring to the `pangoLineageDefinitionFilename` in the "preprocessing config", correct? It's not mandatory there.

**Comment by corneliusroemer** [comment]
Ok, so I get this error only because it's specified but then empty.

I was thinking that the preprocessing config uses default values - so how does one overwrite it to not need to exist? set to null?

```
lapis-silo-1  | [2024-03-26 10:56:37.928] [logger] [error] [api.cpp:297] filesystem error: Alias key file /preprocessing/input/pangolineage_alias.json does not exist: No error information
```

**Comment by fengelniederhammer** [comment]
Not specifying at all should work. 

But we should check as part of #129 what other versions of "not setting it" do.

**Comment by corneliusroemer** [comment]
Indeed it does seem to work without setting that field - so it seems that by default this isn't set?

**Comment by fengelniederhammer** [comment]
> Indeed it does seem to work without setting that field - so it seems that by default this isn't set?

Yes - as the docs state, by default it's unset. ;)

**Comment by fengelniederhammer** [comment]
The question was answered, it's currently mentioned in the docs. And #458 will remove the config value.
