### ISSUE TITLE
Improve linter phase speed in CI

### ISSUE THREAD

**Issue by pflanze** [GenSpectrum/LAPIS-SILO#392]
Everything in CI runs in 2 minutes except the linter phase takes more than 25 minutes. This slows down the reaction time, e.g. notification messages come up, one visits the ticket but doesn't review since the CI hasn't given the OK yet. So one then comes back next day or so when scanning GitHub messages. Or the review was done but the author can't merge yet.

**Comment by pflanze** [comment]
Also, commits that don't touch any source files could skip running clang-tidy completely.

**Comment by Taepper** [comment]
> Can clang-tidy benefit from caching? I use ccache for builds and it helps enormously. Of course that will need a persistent cache.

Oh, yes. This might be a big culprit. I thought that enabling the linter was inherently bad for caching, but this does not need to be the case. With the new github image based caching for dependencies, investigations regarding the caching of the compilation step might lead to new insight

**Comment by pflanze** [comment]
Also, what things does it do other than checking that the formatting is like clang-format does? Because that part could be done by running clang-format (which takes ~1 s) and checking if there are changes.
