### ISSUE TITLE
Unclear error: Parser Error: syntax error at or near ".2"

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS-SILO#408]
I've run into the following preprocessing parser error that isn't really actionable without diving into SILO code:

```
[2024-05-07 18:15:13.483] [logger] [error] [api.cpp:278] Parser Error: syntax error at or near ".2"
LINE 3: ...S "dataUseTermsRestrictedUntil",list_string_agg(flatten([list_transform(aminoA...
                                                  ^
```

Even looking at the code doesn't help much as the line number is just from the catch part. No clue where the parser comes from:
https://github.com/GenSpectrum/LAPIS-SILO/blob/b7238a8ddced5c2661d8778b838c3a5aa0bd860c/src/silo_api/api.cpp#L278

**Comment by chaoran-chen** [comment]
How did you call it and what is the input?
