### ISSUE TITLE
Remove ndjsonInputFile option and unify code paths

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#419]
The current abstraction for input files feels quite off.

It does not really make sense that there is a `metadataInputFilename` and `ndjsonInputFilename` competing, one of which describes format, the other the type of data. These should be unified with an automatic detection of the code paths to choose.

That sequences can only be provided externally in `.fasta` files, when specifying a `metadataInputFilename`, is also very unintuitive

**Comment by fengelniederhammer** [comment]
Irrelevant due to #562
