### ISSUE TITLE
Allow more diverse sequence names

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#465]
A `-` in a sequence name currently breaks the preprocessing. This should be fixed and be made more robust overall by removing the sequence names from most of the SQL statements

**Comment by theosanderson** [comment]
We have just hit this too with a user, with `gag-pol` for HIV. Any estimate on a timeline for this? No pressure just good to figure out the approach on our side.

**Comment by Taepper** [comment]
I think mid-july is a good estimate

**Comment by theosanderson** [comment]
Thanks!
