### ISSUE TITLE
Validate that the default sequence name is present in the database at startup

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS-SILO#475]
In #471 it was raised the issue, that the default sequence name defined in the database config does not have to be a valid sequence name. Add a check to this during startup of the database, so we can be sure in the queries, that the default sequence name is always present. Then remove the check in `insertion_contains.cpp`

**Comment by Taepper** [comment]
It should be resolved with #454 . We will verify after and close accordingly
