### ISSUE TITLE
Replace <cassert> usage with a PANIC based `assert`

### ISSUE THREAD

**Issue by pflanze** [GenSpectrum/LAPIS-SILO#505]
The `assert` from `#include <cassert>` aborts on failures. Instead write one that uses our new `PANIC` macro, and include or use that instead.

**Comment by pflanze** [comment]
As per @Taepper's hint, C's (cassert) assert is eliminated if `-DNDEBUG` (https://en.cppreference.com/w/cpp/error/assert). Could emulate this.

Or could e.g. offer an `ASSERT` which checks the assertion even if `NDEBUG` is set, and an `NASSERT` which behaves like `assert` from C. Because most assertions could stay in release builds without the performance downside (Todo: overview over other project's approaches.)

**Comment by Taepper** [comment]
I see, I like this, fill me in on the details on Monday?

**Comment by fengelniederhammer** [comment]
Was done by #546 and #571
