### ISSUE TITLE
String search with regular expressions

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#517]
We want to be able to filter String columns with regular expressions.

We will implement this with Google's RE2 library

**Comment by corneliusroemer** [comment]
Nice, thanks! 

Previous issue here is #404

**Comment by Taepper** [comment]
Oh, thank you! I should definitely do better bookkeeping for the SILO issues

**Comment by corneliusroemer** [comment]
Doesn't matter 😄 GitHub is really terrible at surfacing duplicates
