### ISSUE TITLE
Docker Image cannot be pulled 

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/LAPIS-SILO#566]
I am unable to pull the docker image: 
```
 docker pull ghcr.io/genspectrum/lapis-silo
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/genspectrum/lapis-silo/manifests/latest": denied: denied
```

**Comment by anna-parker** [comment]
Also using the suggested command when clicking on available containers on the right side does leads to the same access denied error: 
```
docker pull ghcr.io/genspectrum/lapis-silo:commit-d29b2f267274db5708e857b22240c782a3fa2e80
Error response from daemon: Head "https://ghcr.io/v2/genspectrum/lapis-silo/manifests/commit-d29b2f267274db5708e857b22240c782a3fa2e80": denied: denied
```

**Comment by chaoran-chen** [comment]
I've no trouble running `docker pull ghcr.io/genspectrum/lapis-silo`. Is it possible that you are logged in into GitHub's Docker registry but the token is outdated? Try `docker logout ghcr.io` and then pull again.

**Comment by fengelniederhammer** [comment]
The images are public. You can also pull them if you have a valid login. If you don't have a valid login then you cannot pull any image.
I'm closing this. Feel free to reopen if the problem persists.

**Comment by chaoran-chen** [comment]
Exactly, you can only pull if you either are **not** logged in or have a valid login, but GitHub rejects all requests if you use an invalid/outdated login token.
