### ISSUE TITLE
Check how LAPIS can implement the `mutations=123` filter

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS-SILO#59]
In LAPIS it should be possible to filter a mutation for `123`, meaning:
* There is a mutation at position 123
* The filter only considers non-ambiguitiy codes, i.e. suppose the reference genome has an A at position 123, then `123` should mean `123G or 123C or 123T`.

Does SILO already support this? How? Do we need to implement something such that it works?

**Comment by Taepper** [comment]
Resolved by #109
