### ISSUE TITLE
Make sure that nucleotide positions start at 1

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS-SILO#61]
See https://github.com/GenSpectrum/LAPIS/pull/158#discussion_r1152912906

Check and eventually fix.

**Comment by Taepper** [comment]
I will push the necessary change once we have less open pull requests

**Comment by fengelniederhammer** [comment]
@Taepper has this been fixed with https://github.com/GenSpectrum/LAPIS-SILO/pull/141?

**Comment by Taepper** [comment]
Yes, it did, I forgot to close it. For completeness I will commit a PR that shows that the position is now in all cases (including the mutation distribution) 1-indexed
