### ISSUE TITLE
Include Amino Acid Insertions

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS-SILO#87]
Store amino acid insertions in the database and make them queryable.

Details:
- Probably create subtasks and link them here to split this into smaller bits.

**Comment by fengelniederhammer** [comment]
@Taepper @danielgrittner does #166 implement this?

**Comment by Taepper** [comment]
Not yet. I would provide the PR that generalizes #166 to amino acids
